In [3]:
import numpy as np


In [4]:
np.__version__

'2.4.2'

In [5]:
#numpy 1D, 2D , 3D Array 
a1D = np.array([1,2,3,4])
a1D


array([1, 2, 3, 4])

In [6]:
print(type(a1D))

<class 'numpy.ndarray'>


In [7]:
# DocString 
help(np.array)

Help on built-in function array in module numpy:

array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, ndmax=0, like=None)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if obj is
        a nested sequen

In [8]:
a1D.shape # 1D array of length 4

(4,)

In [9]:
a1D.size # length

4

In [10]:
len(a1D)

4

In [11]:
# 2D array list of list
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr
type(arr)

numpy.ndarray

In [12]:
arr.shape

(2, 4)

In [14]:
arr.size

8

In [16]:
arr.__len__

<method-wrapper '__len__' of numpy.ndarray object at 0x000001DEDF78E0D0>

In [ ]:
a3D_list = [[[1,2,3],[2,3,4],[4,5,6]]]
a3D = np.array(a3D_list)
print(a3D)


[[[1 2 3]
  [2 3 4]
  [4 5 6]]]


In [20]:
type(a3D)

numpy.ndarray